<?php
declare(strict_types=1);

// QrCodeGenerator SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

QrCodeGeneratorUtility::setRegistrar(function (QrCodeGeneratorUtility $u): void {
    $u->clean = [QrCodeGeneratorClean::class, 'call'];
    $u->done = [QrCodeGeneratorDone::class, 'call'];
    $u->make_error = [QrCodeGeneratorMakeError::class, 'call'];
    $u->feature_add = [QrCodeGeneratorFeatureAdd::class, 'call'];
    $u->feature_hook = [QrCodeGeneratorFeatureHook::class, 'call'];
    $u->feature_init = [QrCodeGeneratorFeatureInit::class, 'call'];
    $u->fetcher = [QrCodeGeneratorFetcher::class, 'call'];
    $u->make_fetch_def = [QrCodeGeneratorMakeFetchDef::class, 'call'];
    $u->make_context = [QrCodeGeneratorMakeContext::class, 'call'];
    $u->make_options = [QrCodeGeneratorMakeOptions::class, 'call'];
    $u->make_request = [QrCodeGeneratorMakeRequest::class, 'call'];
    $u->make_response = [QrCodeGeneratorMakeResponse::class, 'call'];
    $u->make_result = [QrCodeGeneratorMakeResult::class, 'call'];
    $u->make_point = [QrCodeGeneratorMakePoint::class, 'call'];
    $u->make_spec = [QrCodeGeneratorMakeSpec::class, 'call'];
    $u->make_url = [QrCodeGeneratorMakeUrl::class, 'call'];
    $u->param = [QrCodeGeneratorParam::class, 'call'];
    $u->prepare_auth = [QrCodeGeneratorPrepareAuth::class, 'call'];
    $u->prepare_body = [QrCodeGeneratorPrepareBody::class, 'call'];
    $u->prepare_headers = [QrCodeGeneratorPrepareHeaders::class, 'call'];
    $u->prepare_method = [QrCodeGeneratorPrepareMethod::class, 'call'];
    $u->prepare_params = [QrCodeGeneratorPrepareParams::class, 'call'];
    $u->prepare_path = [QrCodeGeneratorPreparePath::class, 'call'];
    $u->prepare_query = [QrCodeGeneratorPrepareQuery::class, 'call'];
    $u->graphql_body = [QrCodeGeneratorGraphql::class, 'body'];
    $u->graphql_errors = [QrCodeGeneratorGraphql::class, 'errors'];
    $u->result_basic = [QrCodeGeneratorResultBasic::class, 'call'];
    $u->result_body = [QrCodeGeneratorResultBody::class, 'call'];
    $u->result_headers = [QrCodeGeneratorResultHeaders::class, 'call'];
    $u->transform_request = [QrCodeGeneratorTransformRequest::class, 'call'];
    $u->transform_response = [QrCodeGeneratorTransformResponse::class, 'call'];
});
